[tools]
elixir = "latest"
elixir-ls = "latest"
erlang = "latest"
gleam = "1.12.0"
node = "22.15.0"
usage = "latest"
uv = "0.9.2"

[settings]
idiomatic_version_file_enable_tools = ["node"]
asdf_compat = true
