[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = "t"
run  = "plugin smart-tab"
desc = "Create a tab and enter the hovered directory"

# Copy to system clipboard
[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on = [ "M", "m" ]
run = "plugin gvfs -- select-then-mount --jump"
desc = "Select device to mount and jump to its mount point"

[[mgr.prepend_keymap]]
on = [ "M", "u" ]
run = "plugin gvfs -- select-then-unmount"
desc = "Select device then unmount"

[[mgr.prepend_keymap]]
on = [ "M", "a" ] 
run = "plugin gvfs -- add-mount"
desc = "Add a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "e" ]
run = "plugin gvfs -- edit-mount"
desc = "Edit a GVFS mount URI"

[[mgr.prepend_keymap]]
on = [ "M", "r" ]
run = "plugin gvfs -- remove-mount"
desc = "Remove a GVFS mount URI"
