session: Dotfiles

root: ~/.dotfiles

windows:
  - name: Dots
    root: .
    selected: true
    layout: main-horizontal

  - name: Hyprland
    root: configs/hypr/.config/hypr/
    selected: true
    layout: main-horizontal
    commands:
      - nvim hyprland.conf

  - name: Neovim
    root: configs/nvim/.config/nvim/
    selected: true
    layout: main-horizontal
    commands:
      - nvim init.lua

  - name: Waybar
    root: configs/waybar/.config/waybar/
    selected: true
    layout: main-horizontal
    commands:
      - nvim config

  - name: Smug
    root: configs/smug/.config/smug/
    selected: true
    layout: main-horizontal
    commands:
      - nvim -c 'Neotree toggle'

  - name: Tmux
    root: configs/tmux/.config/tmux/
    selected: true
    layout: main-horizontal
    commands:
      - nvim tmux.conf
