session: Dotfiles

root: ~/.dotfiles

windows:
  - name: Dots
    root: .
    selected: true
    layout: main-horizontal

  - name: Niri
    root: configs/niri/.config/niri/
    selected: true
    layout: main-horizontal
    commands:
      - nvim config.kdl

  - name: Neovim
    root: configs/nvim/.config/nvim/
    selected: true
    layout: main-horizontal
    commands:
      - nvim init.lua

  - name: Smug
    root: configs/smug/.config/smug/
    selected: true
    layout: main-horizontal
    commands:
      - nvim -c 'Neotree toggle'

  - name: Tmux
    root: configs/tmux/.config/tmux/
    selected: true
    layout: main-horizontal
    commands:
      - nvim tmux.conf
